
/*
 * Generated by ChokoEditor.
 * DO NOT EDIT.
 */
#include "loader_base.hpp"

CE_BEGIN_PL_NAMESPACE

ScriptLoaderImpl _ScriptLoaderImpl::getld(const std::string& s) {
	auto& res = _lds[s];
	if (!res) {
		if (0) {}
			else if (s == "texx.hpp"){
				res = std::make_shared<_ScrLdImpl_Texx>();
			}
		}
		return res;
	}

CE_END_PL_NAMESPACE	
