# Generated by ChokoEditor. DO NOT EDIT.

target_sources(chokoeditor_project PRIVATE
	${CMAKE_SOURCE_DIR}/system/src/loaders/load_Cam.cpp
	${CMAKE_SOURCE_DIR}/system/src/loaders/load_Ppl.cpp
	${CMAKE_SOURCE_DIR}/system/src/loaders/load_Texx.cpp
)